version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - run:
          name: Build and push frontend application image
          command: |
            git clone https://github.com/kirubakarthikeyan/spring-petclinic-angular.git
            cd ./spring-petclinic-angular
            TAG=v$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/petclinic_frontend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/petclinic_frontend:$TAG
            echo "test"
workflows:
  version: 2
  build:
    jobs:
      - build